version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: mon_marche_user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
  app:
    build: .
    environment:
      DB_HOST: db
      DB_USER: mon_marche_user
      DB_PASSWORD: mypassword
      DB_NAME: mydb
      DB_PORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      - db
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db